CarpeLibrum/Areas/Admin/Controllers/SchoolController.cs
using Librum.DataAccess.Data;
using Librum.DataAccess.Repository;
using Librum.DataAccess.Repository.IRepository;
using Librum.Models;
using Librum.Models.ViewModels;
using Librum.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing.Constraints;
using System.Collections.Generic;
using System.Data;
using System.Reflection.Metadata.Ecma335;

namespace CarpeLibrum.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class SchoolController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public SchoolController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<School> objProdList = _unitOfWork.SchoolRepository.GetAll().ToList();
            
            return View(objProdList); 
        }

        public IActionResult Create()
        {
            return View(new School()); 
        }

        [HttpPost]
        public IActionResult Create(School c) 
        {

            if (ModelState.IsValid)
            {
                
                _unitOfWork.SchoolRepository.Add(c);
                _unitOfWork.Save();
                TempData["success"] = "School created successfully!";
                return RedirectToAction("index");
            }

                return View(c);
            
        }

        public IActionResult Edit(int? id)
        {
            if(id==0||id==null)
            {
                return NotFound();
            }
            School schoolFromDb = _unitOfWork.SchoolRepository.Get(u => u.Id == id);
            
            if (schoolFromDb == null)
            {
                return NotFound();
            }
            return View(schoolFromDb);
        }

        [HttpPost]
        public IActionResult Edit(School c)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.SchoolRepository.Update(c);
                _unitOfWork.Save();
                TempData["success"] = "School updated successfully!";
                return RedirectToAction("index");
            }
                return View(c);

        }

        //public IActionResult Upsert(int? id)
        //{
        //    //ViewBag.CategoryList = CategoryList;
        //    ProductViewModel pvm = new()
        //    {
        //        CategoryList = _unitOfWork.CategoryRepository.GetAll().Select(u => new SelectListItem
        //        {
        //            Text = u.Name,
        //            Value = u.Id.ToString()
        //        }),
        //        Product = new Product()
        //    };
        //    if (id == null||id==0) // this means its a create method
        //    {
        //        return View(pvm);
        //    }
        //    else //edit functionality
        //    {
        //        pvm.Product = _unitOfWork.ProductRepository.Get(u => u.Id == id);
        //        return View(pvm);
        //    }
            
        //}
        //[HttpPost]
        //public IActionResult Upsert(ProductViewModel pvm, IFormFile? file)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        string wwwRootPath = _webHostEnvironment.WebRootPath;
        //        if (file != null) 
        //        {
        //            string fileName = Guid.NewGuid().ToString()+Path.GetExtension(file.FileName);
        //            string productPath = Path.Combine(wwwRootPath, @"images\product");
        //            using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
        //            {
        //                file.CopyTo(fileStream);
        //            }
        //            pvm.Product.ImageUrl = @"images\product\" + fileName;
        //        }

        //        _unitOfWork.ProductRepository.Add(pvm.Product);
        //        _unitOfWork.Save();
        //        TempData["success"] = "Product created successfully!";
        //        return RedirectToAction("Index");
        //    }
        //    else
        //    {
        //        pvm.CategoryList = _unitOfWork.CategoryRepository.GetAll().Select(u => new SelectListItem
        //        {
        //            Text = u.Name,
        //            Value = u.Id.ToString()
        //        });
        //    }
        //    return View(pvm);
        //}
        //public IActionResult Edit(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }
        //    Product productFromDb = _unitOfWork.ProductRepository.Get(c => c.Id == id);
        //    if (productFromDb == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(productFromDb);
        //}
        //[HttpPost]
        //public IActionResult Edit(Product c)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        _unitOfWork.ProductRepository.Update(c);
        //        _unitOfWork.Save();
        //        TempData["success"] = "Product updated successfully!";
        //        return RedirectToAction("Index");
        //    }
        //    return View();
        //}

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            School c = _unitOfWork.SchoolRepository.Get(c => c.Id == id);
            if (c == null)
            {
                return NotFound();
            }
            return View(c);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            School c = _unitOfWork.SchoolRepository.Get(p => p.Id == id);
            if (c == null)
            {
                TempData["error"] = "Error while deleting";
                return NotFound();
            }
            _unitOfWork.SchoolRepository.Delete(c);
            _unitOfWork.Save();
            TempData["success"] = "School deleted successfully!";
            return RedirectToAction("Index");

        }


        #region API calls

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Product> objProdList = _unitOfWork.ProductRepository.GetAll(includeProperties: "Category").ToList();
            return Json(new { data = objProdList });
        }

        #endregion
    }
}

CarpeLibrum/Areas/Admin/Views/School/Create.cshtml
@model School
@{
    ViewData["Title"] = "Create Product";
}
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg- m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-primary py-2">Create School</h2>
            </div>
        </div>
    </div>
    <div class="card-body p4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="border p-3">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3 row p-1">
                    <label asp-for="Name" class="p-0"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label asp-for="PhoneNumber" class="p-0"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label asp-for="StreetAddress" class="p-0"></label>
                    <input asp-for="StreetAddress" class="form-control" />
                    <span asp-validation-for="StreetAddress" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label asp-for="City" class="p-0"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label asp-for="State" class="p-0"></label>
                    <input asp-for="State" class="form-control" />
                    <span asp-validation-for="State" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label asp-for="PostalCode" class="p-0"></label>
                    <input asp-for="PostalCode" class="form-control" />
                    <span asp-validation-for="PostalCode" class="text-danger"></span>
                </div>
                </div>
                <div class="row">
                    <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success form-control">Create</button>
                    </div>
                    <div class="col-6 col-md-3">
                            <a asp-controller="School" asp-action="Index" class="btn btn-secondary form-control">Back to List</a>
                    </div>
                </div>
        </form>
    </div>
    
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

CarpeLibrum/Areas/Admin/Views/School/Delete.cshtml
@model School
@{
    ViewData["Title"] = "Delete School";
}
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg- m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-primary py-2">Delete School</h2>
            </div>
        </div>
    </div>
    <div class="card-body p4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="row">
                <div class="col-12">
                    <div class="border p-3">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="mb-3 row p-1">
                            <label asp-for="Name" class="p-0"></label>
                            <input asp-for="Name" class="form-control" disabled />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="mb-3 row p-1">
                            <label asp-for="PhoneNumber" class="p-0"></label>
                            <input asp-for="PhoneNumber" class="form-control" disabled />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="mb-3 row p-1">
                            <label asp-for="StreetAddress" class="p-0"></label>
                            <input asp-for="StreetAddress" class="form-control" disabled />
                            <span asp-validation-for="StreetAddress" class="text-danger"></span>
                        </div>
                        <div class="mb-3 row p-1">
                            <label asp-for="City" class="p-0"></label>
                            <input asp-for="City" class="form-control" disabled />
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="mb-3 row p-1">
                            <label asp-for="State" class="p-0"></label>
                            <input asp-for="State" class="form-control" disabled />
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>
                        <div class="mb-3 row p-1">
                            <label asp-for="PostalCode" class="p-0"></label>
                            <input asp-for="PostalCode" class="form-control" disabled />
                            <span asp-validation-for="PostalCode" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success form-control">Delete</button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="School" asp-action="Index" class="btn btn-secondary form-control">Back to List</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CarpeLibrum/Areas/Admin/Views/School/Edit.cshtml
@model School
@{
    ViewData["Title"] = "Create School";
}
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg- m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-primary py-2">Edit School</h2>
            </div>
        </div>
    </div>
    <div class="card-body p4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="row">
                <div class="col-12">
                    <div class="border p-3">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="mb-3 row p-1">
                            <label asp-for="Name" class="p-0"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="mb-3 row p-1">
                            <label asp-for="PhoneNumber" class="p-0"></label>
                            <input asp-for="PhoneNumber" class="form-control" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="mb-3 row p-1">
                            <label asp-for="StreetAddress" class="p-0"></label>
                            <input asp-for="StreetAddress" class="form-control" />
                            <span asp-validation-for="StreetAddress" class="text-danger"></span>
                        </div>
                        <div class="mb-3 row p-1">
                            <label asp-for="City" class="p-0"></label>
                            <input asp-for="City" class="form-control" />
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="mb-3 row p-1">
                            <label asp-for="State" class="p-0"></label>
                            <input asp-for="State" class="form-control" />
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>
                        <div class="mb-3 row p-1">
                            <label asp-for="PostalCode" class="p-0"></label>
                            <input asp-for="PostalCode" class="form-control" />
                            <span asp-validation-for="PostalCode" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 col-md-3">
                            <button type="submit" class="btn btn-success form-control">Update</button>
                        </div>
                        <div class="col-6 col-md-3">
                            <a asp-controller="School" asp-action="Index" class="btn btn-secondary form-control">Back to List</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

CarpeLibrum/Areas/Admin/Views/School/Index.cshtml
@model List<School>
@{
    ViewData["Title"] = "Product List";
}
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg- m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-primary py-2">School List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            

        <div class="col-12 text-end">
            <a class="btn btn-success" asp-controller="School" asp-action="Create"> <i class="bi bi-plus-square"></i> &nbsp Add School</a>
        </div>
        </div>
        <table id="#tblData" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Phone number</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model)
            {
                <tr>
                    <td>@p.Name</td>
                    <td>@p.StreetAddress</td>
                    <td>@p.City                                                                                                                                                                   e</td>
                    <td>@p.State</td>
                    <td>@p.PhoneNumber</td>
                    <td>
                        <div class=" w-75 btn-group" role="group">
                            <a asp-controller="School" asp-action="Edit" asp-route-id="@p.Id" class="btn btn-info mx-2"><i class="bi bi-pencil-fill"></i></a>
                            <a asp-controller="School" asp-action="Delete" asp-route-id="@p.Id" class="btn btn-danger mx-2"><i class="bi bi-trash3-fill"></i></a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    </div>
</div>

@section Scripts{
    <script src="~/js/product.js"></script>
}